
export const DOMstrings = {

    timeSlot: '.timeSlot',
    timeSlotDiv: '#timeslot',
    active: '.active',
    hours: '.hours',
    subAbs: '.subabs',
    subAbTime: '.subabtime',
    coDiv: '#co',
    company: '#company',
    freq: '#frequency',
    date: '#date',
    teacher: '.teacher',
    adultsSelect: '.adults',
    adultsDiv: '#adults',
    kidsTeensSelect: '.kidsTeens',
    kidsTeensDiv: '#kidsTeens',
    chatSelect: '.chat',
    chatDiv: '#chat',
    btn: '.addBtn',
    itemContainer: '.report__body',
    absencesContainer: '.absences__list',
    subsContainer: '.subs__list',
    companiesContainer: '.companies__list',
    coursesContainer: '.courses__list',
    totalhrs: '.totalhrs',
    subs_tot: '.total_sub',
    companies_tot: '.total_cmp',
    abs_tot: '.total_abs',
    courses_tot:  '.total_crs',
    period_from: '#from',
    period_to: '#to'
};